<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>csharp2ts</ToolCommandName>
    <PackageOutputPath>../nupkg</PackageOutputPath>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/ormesam/CSharp2TS</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ormesam/CSharp2TS</RepositoryUrl>
    <Title>$(AssemblyName)</Title>
    <Authors>Sam Orme</Authors>
    <PackageVersion>0.0.38-alpha</PackageVersion>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>
    <Copyright>Sam Orme</Copyright>
    <PackageTags>csharp2ts;typescript-generator</PackageTags>
    <PackageReleaseNotes>Add TSConstants attribute for generating TypeScript constants from C# const fields</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <Description>CSharp2TS.CLI is a tool to generate TypeScript files for C# classes, enums, constants and API endpoints. Requires the CSharp2TS.Core nuget package to be installed on the target project.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="System.CodeDom" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp2TS.Core\CSharp2TS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="PACKAGE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Templates\TSAxiosApiClientTemplate.tt">
      <LastGenOutput>TSAxiosApiClientTemplate.cs</LastGenOutput>
      <Generator>TextTemplatingFilePreprocessor</Generator>
    </None>
    <None Update="Templates\TSInterfaceTemplate.tt">
      <LastGenOutput>TSInterfaceTemplate.cs</LastGenOutput>
      <Generator>TextTemplatingFilePreprocessor</Generator>
    </None>
    <None Update="Templates\TSEnumTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>TSEnumTemplate.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Templates\TSAxiosApiClientTemplate.cs">
      <DependentUpon>TSAxiosApiClientTemplate.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Templates\TSInterfaceTemplate.cs">
      <DependentUpon>TSInterfaceTemplate.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Templates\TSEnumTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TSEnumTemplate.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
