<Project Sdk="Microsoft.NET.Sdk">
    
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>$(AssemblyName)</Title>
    <Authors>Sam Orme</Authors>
    <Company />
    <PackageProjectUrl>https://github.com/ormesam/CSharp2TS</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ormesam/CSharp2TS</RepositoryUrl>
    <PackageOutputPath>../nupkg</PackageOutputPath>
    <PackageVersion>0.0.8-alpha</PackageVersion>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>
    <Copyright>Sam Orme</Copyright>
    <PackageTags>csharp2ts;typescript-generator</PackageTags>
    <PackageReleaseNotes>Add TSConstants attribute for generating TypeScript constants from C# const fields; allow TSExclude on fields</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <Description>CSharp2TS.Core is a lightweight package that contains the attributes required for the **CSharp2TS.CLI** dotnet tool to generate TypeScript models and API services.</Description>
  </PropertyGroup>
    
  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="PACKAGE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
    
</Project>
